In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr + 5  # numpy will add 5 at each item (element by element)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [7]:
arr + arr  # (doubled every number). Can only if the arrays are from the same size 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr / arr  # devide by it self

/var/folders/f0/4z_vbr3x0sv42rr3r_9jcw8w0000gn/T/ipykernel_9808/3358745301.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr  # devide by it self


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

NumPy comes with many universal array functions which can be called on every element of array. Look them up!

In [11]:
np.sqrt(arr)  # square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
np.sin(arr) 

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [13]:
np.log(arr)

/var/folders/f0/4z_vbr3x0sv42rr3r_9jcw8w0000gn/T/ipykernel_9808/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr.sum()  # Sums up every element in the array

45

In [16]:
arr.mean()  # Takes the average

4.5

In [17]:
arr.max()  # Highest element in the array

9

In [18]:
arr.var() # variance

8.25

In [19]:
arr.std()  # standard deviation

2.8722813232690143

Universal array functions with 2-d arrays

In [20]:
arr = np.arange(0, 25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
# Or (shorter)
arr = np.arange(0, 25).reshape(5, 5)

In [24]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr.shape

(5, 5)

In [26]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr.sum()  # sums up all elements

300

In [28]:
arr.sum(axis=0)  # 0 = across the rows (vertical) = sums up all the elements in the column

array([50, 55, 60, 65, 70])

In [29]:
arr.sum(axis=1)  # 1 = across the colums (horizontal) sums up all the elements in the rows

array([ 10,  35,  60,  85, 110])