Numpy (Numeric Python and is a Python Package or module)
- Used in Data Analysis and created to tackle computational problems
- A collection of pre written functions, classes and methods wich are capable of handling and manipulating data and calculating results.
- The main feature is it's easy to use and manipulate arrays

Arrray:
- Type of data structure wich stores elements and refer to their values via integers indices

Why:
- Because the package is incredibly computationally stable and efficient
- It serves as a basis for many other packages like SciPy and even pandas
- Has its roots in C which results in shorter computation time

When:
- Whenever we want to compute a lot of values for analysis and deal with some abstract ideas like vectors (one dimensional) and matrices (matrix: multiple dimensions)
- Since it's both stable and fast, we can rely on numpy to estimate statistical values and deal with linear algebra.
- to import data into Python directly and help pre-process it
- fantastic for generating random tests by providing enough arguments we can create arrays of differt size, which means they can contain different number of elements and fill them with data from specific statistical distribution

Ndarray (class):
- Short for N-Dimensional array
- These arrays resemble Python lists because the store ordered data and we use [] to display them
- Arrays are far more useful when it comes to computing mathematical values. Because array operations work element wise.
- Beside of that, numpy is full of universal functions and methods designed specifically for working with Ndarray, unlike general Python functions they usually compile faster and offer great convenience through two operations: broadcasting an typecasting

# Importing NumPy

In [2]:
import numpy as np

# Using NumPy

In [3]:
mylist = [1, 2, 3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
mylist

[1, 2, 3]

In [7]:
myarr = np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 20 ,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))  # first rows second colums

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.linspace(0, 10, 3)  # evenly spaced including stopping point 10 (not the same as (a)range)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [19]:
np.eye(5)  # not used in course

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(5,2)

array([[0.24067903, 0.07036408],
       [0.36213057, 0.82428391],
       [0.55559348, 0.41060431],
       [0.29892042, 0.4170251 ],
       [0.43074612, 0.20178716]])

In [21]:
np.random.randn(2,3)

array([[ 0.91514117, -2.30493044,  1.00783105],
       [-0.94826509,  1.53115371,  0.58322624]])

In [22]:
np.random.randint(0, 101)  # one whole number not incl. stop (101)

73

In [23]:
np.random.randint(0, 101, 10)  # ten whole number between 0 and 100 (not incl 101)

array([16, 81, 89, 41, 34, 87, 41, 94, 29, 66])

In [43]:
array2 = np.random.seed(42)  # set of random numbers (same random numbers) 42 can be everything (test differtent models on same numbers)
array2 = np.random.rand(4)
array2

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [25]:
arr = np.arange(0, 25)  # not including 25

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
# different shape
arr.reshape(5,5)  # 5 rows and 5 columns

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr = np.random.randint(0, 101, 10)  # 10 random integers

In [29]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [30]:
# Max value
ranarr.max()

99

In [31]:
# Min value
ranarr.min()

2

In [32]:
ranarr.argmax()  # index position max value

5

In [33]:
ranarr.argmin()  # index position min value

7

In [34]:
ranarr.dtype

dtype('int64')

In [35]:
arr.shape  # reports 25 items

(25,)

In [36]:
arr = arr.reshape(5, 5)

In [37]:
arr.shape  # reports 5 by 5 columns and rows

(5, 5)

In [38]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])