In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [7]:
myarr = np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0, 20 ,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))  # first rows second colums

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.linspace(0, 10, 3)  # evenly spaced including stopping point 10 (not the same as (a)range)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [20]:
np.eye(5)  # not used in course

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(5,2)

array([[0.71613808, 0.43544988],
       [0.33308061, 0.79952503],
       [0.06474035, 0.84748452],
       [0.24267331, 0.3066155 ],
       [0.99068783, 0.77422389]])

In [23]:
np.random.randn(2,3)

array([[ 0.29646793,  1.33197093,  0.87039299],
       [ 0.64203021, -0.16924574, -1.02084237]])

In [24]:
np.random.randint(0, 101)  # one whole number not incl. stop (101)

52

In [25]:
np.random.randint(0, 101, 10)  # ten whole number between 0 and 100 (not incl 101)

array([84, 30, 98, 88, 71, 26, 79, 21, 73, 35])

In [26]:
np.random.seed(42)  # set of random numbers (same random numbers) 42 can be everything (test differtent models on same numbers)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [27]:
arr = np.arange(0, 25)  # not including 25

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
# different shape
arr.reshape(5,5)  # 5 rows and 5 columns

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr = np.random.randint(0, 101, 10)  # 10 random integers

In [31]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [32]:
# Max value
ranarr.max()

99

In [33]:
# Min value
ranarr.min()

2

In [34]:
ranarr.argmax()  # index position max value

5

In [35]:
ranarr.argmin()  # index position min value

7

In [37]:
ranarr.dtype

dtype('int64')

In [38]:
arr.shape  # reports 25 items

(25,)

In [39]:
arr = arr.reshape(5, 5)

In [40]:
arr.shape  # reports 5 by 5 columns and rows

(5, 5)

In [41]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])